name             'tomcat_node'
maintainer       'Adrian Lopez'
maintainer_email 'adrijardi@gmail.com'
license          'All rights reserved'
description      'Configures an standard tomcat node'
version          '1.0.0'
depends          'simple_iptables'
depends          'tomcat'